### ISSUE TITLE
I want all icon on one font !

### ISSUE THREAD

**Issue by othytrigui** [linea-io/Linea-Iconset#6]
Please, anyone have a sollution to my problem and I think a lot of people have the same problem !
I want all the icon fonts on one font ttf / svg / eot / woff ! just one font contain all icons !
Please Help me :)

**Comment by pixi** [comment]
Have you tried https://glyphsapp.com/ ?

**Comment by Suyash-Purwar** [comment]
There's no need to mix all the icon fonts. I have made a PR, clone it and use the same HTML markup as you were using. Everything will work out just fine.

**Comment by suyash-purwar** [comment]
There's no need to mix all the icon fonts. I have made a PR, see the changes I have made and do those same changes in your files and use the same HTML markup as you were using. Everything will work out just fine.
